### ISSUE TITLE
How to prepare resource files for hg38 ?

### ISSUE THREAD

**Issue by ahy1221** [inab/SmartRNASeqCaller#1]
Dear developers,
Thanks for the workflow.
My dataset is aligned to hg38 but not hg19.
I was wondering that is that possible to apply the classification model for hg38 . If so, how to prepare resource files for the whole workflow, especifially for the splice4bp and rnaedit files ?

**Comment by mbosio85** [comment]
Hello,
It is definitely possible to apply the model to hg38.
To prepare the resources you can:
 -  Repmask : just download the bed from UCSC for hg38
 - RNAEdit   : The only way it occurs to me at the moment is to do a [liftover](https://genome.ucsc.edu/cgi-bin/hgLiftOver) of the provided bed from hg19 to hg38. It should work for the vast majority of sites. Otherwise, if you are aware of newer RNA Edit repositories aligned to hg38, you can use those.
 - splice4bp regions : 
   - You can download it from UCSC Table Browser:
       - select the appropriate track (e.g. some gene annotation "GENCODE v29")
       - select output format "BED", click "get output", 
       - then "Create one BED record "introns" plus 0 bases at each end
    - Then run resources/[generate_splice_slice.py](https://github.com/inab/SmartRNASeqCaller/blob/master/resources/generate_intron_slice.py) introns.bed > intron_slice_hg38_4bp.bed

Hope it helps.

Mattia

**Comment by ahy1221** [comment]
Thanks very much.
I have got hg38 resource files successfully following your instruction.

**Comment by travelanywhere** [comment]
Could you maybe put the hg38 resource files somewhere others can use it as well?
