### ISSUE TITLE
filters not compatible with 'chr' in chromosome identifiers.  ie. requires '1' instead of 'chr1'

### ISSUE THREAD

**Issue by brianjohnhaas** [inab/SmartRNASeqCaller#6]
Hi,

I noticed that if the genome being used includes 'chr' in the chromosome identifiers, the various filters aren't working, such as splice adjacency, repeat masker overlap, etc., as none of the resource files contain 'chr' identifiers and none of the resulting 'bed intersect' calls find overlaps.

Genomes downloaded from GENCODE all contain 'chr' identifiers, and this breaks compatibility.

**Comment by mbosio85** [comment]
Hi,

This is a latent issue because for legacy reasons we had to deal with BAMs without the chr and basically we kept it.
I resolved to update the resource folder with : 
  - adding the chr prefix to the default files so by default the tool has compatibility with GENCODE annotation 
  - adding a new set of files with '_nochr_' in the name so that we can have the files without 'chr' in it in case it's needed.

Cheers,
Mattia
